# Generated by Django 4.2.1 on 2023-05-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descritpion', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
