# Generated by Django 4.2 on 2023-05-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swieta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swieta',
            old_name='swieto',
            new_name='descritpion',
        ),
    ]
