# Generated by Django 4.2 on 2023-05-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscope',
            old_name='horoscope',
            new_name='description',
        ),
    ]
