# Generated by Django 4.1.7 on 2023-04-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
    ]
