# Generated by Django 4.1.7 on 2023-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_remove_cities_city_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cities',
        ),
    ]
