# Generated by Django 4.1.7 on 2023-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('date', models.DateField()),
                ('weather_description', models.CharField(max_length=300)),
                ('so2', models.FloatField()),
                ('no2', models.FloatField()),
                ('o3', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm10', models.FloatField()),
                ('co', models.FloatField()),
                ('nh3', models.FloatField()),
            ],
        ),
    ]
