# Generated by Django 4.2 on 2023-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_city_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='no',
            field=models.FloatField(default=0),
        ),
    ]
