# Generated by Django 4.2 on 2023-04-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_city_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='air_pol',
            field=models.FloatField(default=0),
        ),
    ]
