# Generated by Django 4.2 on 2023-04-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_city_air_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
