# Generated by Django 4.2 on 2023-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_city_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_weather',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='weather_pic',
            field=models.CharField(default='', max_length=150),
        ),
    ]
