# Generated by Django 4.2 on 2023-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_city_id_weather_city_weather_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='weather_description_simple',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='city',
            name='weather_description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
