# Generated by Django 4.2 on 2023-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_rename_weather_pic_city_clouds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
