# Generated by Django 4.2 on 2023-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_alter_city_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='grnd_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='sea_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='rain',
            field=models.FloatField(),
        ),
    ]
