# Generated by Django 4.2 on 2023-05-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_city_grnd_level_city_humidity_city_sea_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='grnd_level',
        ),
        migrations.RemoveField(
            model_name='city',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='city',
            name='sea_level',
        ),
    ]
