# Generated by Django 4.2.1 on 2023-05-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_remove_city_grnd_level_remove_city_rain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='air_pol',
            field=models.CharField(default='', max_length=100),
        ),
    ]
