# Generated by Django 4.2.1 on 2023-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0016_alter_city_air_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
